### PR TITLE
Fix output rate when rendering to mp4

### LINKED ISSUE #26: Fix output rate when rendering to mp4
On my system ffmpeg set incorrect framerate by default: 25 instead of 60. It's better to specify it obviously. Could you please add one more -r parameter at the end of the ffmpegArgs.push definition to fix it.

### PR DESCRIPTION
**Pull request by ed-asriyan**
closes #26

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -318,7 +318,8 @@ ${inject.body || ''}
           '-preset', ffmpegOptions.preset,
           '-crf', ffmpegOptions.crf,
           '-movflags', 'faststart',
-          '-pix_fmt', 'yuv420p'
+          '-pix_fmt', 'yuv420p',
+          '-r', fps
```
Comment (transitive-bullshit) [inline index.js:322]: this argument already exists earlier in the args https://github.com/ed-asriyan/puppeteer-lottie/blob/patch-1/index.js#L313

Comment (ed-asriyan) [reply index.js:322]: Yes, but we need the second **-r**

**Comment by transitive-bullshit** [comment]
Thanks @ed-asriyan and sorry for the delay.
